name: CI/CD Workflow

on: [push]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build . -t two-tier-flask-app-new

    - name: Tag and push Docker image to DockerHub
      run: |
        docker tag two-tier-flask-app-new ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask-app-new:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask-app-new:latest

    - name: Deploy using docker-compose
      run: |
        docker-compose down
        docker-compose up -d
